version: '3.8'

services:
  clipmaster:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: clipmaster
    network_mode: host
    volumes:
      - ./downloads:/app/backend/downloads
      - ./frontend:/app/frontend
    restart: unless-stopped
